### PR TITLE
Change the way of adding toolbar buttons to avoid plugin conflicts

### PR DESCRIPTION
**Pull request by Achuan-2**
Using the following code, if there are two or more plugins want to add buttons to the toolbar, only  one plugin can add the buttons successfully while the others will fail, causing conflicts.

```
        this.protyleOptions = {
            toolbar: ["block-ref",
                "a",
                "|",
                "text",
                "strong",
                "em",
                "u",
                "s",
                "mark",
                "sup",
                "sub",
                "clear",
                "|",
                "code",
                "kbd",
                "tag",
                "inline-math",
                "inline-memo",
                "|",
                {
                    name: "insert-smail-emoji",
                    icon: "iconEmoji",
                    hotkey: "⇧⌘I",
                    tipPosition: "n",
                    tip: this.i18n.insertEmoji,
                    click(protyle: Protyle) {
                        protyle.insert("😊");
                    }
                }],
        };
```
SiYuan  will add the plugin method `updateProtyleToolbar` in v3.1.12, see https://github.com/siyuan-note/plugin-sample/issues/24
```js
import {IMenuItem} from "siyuan/types";
updateProtyleToolbar(toolbar: Array<string | IMenuItem>) {
    toolbar.push("|")
    toolbar.push({
        name: "insert-smail-emoji",
        icon: "iconEmoji",
        hotkey: "⇧⌘I",
        tipPosition: "n",
        tip: this.i18n.insertEmoji,
        click(protyle: Protyle) {
            protyle.insert("😊");
        }
    })
    return toolbar;
}

```

### CODE REVIEW

**Comment by anarion80** [comment]
Excellent, thanks @Achuan-2 ! I was just mentally preparing to tackle this. So I understand we need to wait for Siyuan release v3.1.12 before merging this. Can you also then update plugin.json `"minAppVersion": "3.0.12",` to that required version already under this PR?

**Comment by anarion80** [comment]
And then also remove `export const builtinEditTools: Array<string | IToolbarItem> ` from `const.ts` as it will not be needed anymore.

**Comment by anarion80** [comment]
Thanks! Let's then wait for SiYuan new release.

**Comment by Achuan-2** [comment]
ok, I have changed these files.

**Pull request merged**
